#!/bin/bash

set -eu
set -o pipefail

yum install -y epel-release
yum install -y python34
yum install -y python-pip
yum install -y python34-pip
yum install -y python-pep8
yum install -y python-markdown

